// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapinfortrend = map[string]*DeviceData{
    "EonStor-GSe-Pro-3008": {
        Manufacturer: "Infortrend",
        Model: "EonStor-GSe-Pro-3008",
        Slug: "infortrend-eonstor-gse-pro-3008",
        UHeight: 2,
        PartNumber: "EonStor-GSe-Pro-3008",
        IsFullDepth: false,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 11.07,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "EonStor-GSe-Pro-3012": {
        Manufacturer: "Infortrend",
        Model: "EonStor-GSe-Pro-3012",
        Slug: "infortrend-eonstor-gse-pro-3012",
        UHeight: 2,
        PartNumber: "EonStor-GSe-Pro-3012",
        IsFullDepth: false,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 12.08,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "EonStor-GSe-Pro-3016": {
        Manufacturer: "Infortrend",
        Model: "EonStor-GSe-Pro-3016",
        Slug: "infortrend-eonstor-gse-pro-3016",
        UHeight: 3,
        PartNumber: "EonStor-GSe-Pro-3016",
        IsFullDepth: false,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 14.81,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "eth3", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
