// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapuniview = map[string]*DeviceData{
    "IPC2105SB-ADF16KM-I0": {
        Manufacturer: "Uniview",
        Model: "IPC2105SB-ADF16KM-I0",
        Slug: "uniview-ipc2105sb-adf16km-i0",
        UHeight: 0,
        PartNumber: "IPC2105SB-ADF16KM-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 420,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2108SB-ADF16KM-I0": {
        Manufacturer: "Uniview",
        Model: "IPC2108SB-ADF16KM-I0",
        Slug: "uniview-ipc2108sb-adf16km-i0",
        UHeight: 0,
        PartNumber: "IPC2108SB-ADF16KM-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 420,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2122LB-AF28-DL-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC2122LB-AF28-DL-ECO",
        Slug: "uniview-ipc2122lb-af28-dl-eco",
        UHeight: 0,
        PartNumber: "IPC2122LB-AF28-DL-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 150,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2122LB-AF28-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC2122LB-AF28-ECO",
        Slug: "uniview-ipc2122lb-af28-eco",
        UHeight: 0,
        PartNumber: "IPC2122LB-AF28-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 150,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2122LB-AF28K-DL": {
        Manufacturer: "Uniview",
        Model: "IPC2122LB-AF28K-DL",
        Slug: "uniview-ipc2122lb-af28k-dl",
        UHeight: 0,
        PartNumber: "IPC2122LB-AF28K-DL",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 240,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2122LB-ASF28K-A": {
        Manufacturer: "Uniview",
        Model: "IPC2122LB-ASF28K-A",
        Slug: "uniview-ipc2122lb-asf28k-a",
        UHeight: 0,
        PartNumber: "IPC2122LB-ASF28K-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 210,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2122LB-SF28-A": {
        Manufacturer: "Uniview",
        Model: "IPC2122LB-SF28-A",
        Slug: "uniview-ipc2122lb-sf28-a",
        UHeight: 0,
        PartNumber: "IPC2122LB-SF28-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 270,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2124LB-AF28-DL-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC2124LB-AF28-DL-ECO",
        Slug: "uniview-ipc2124lb-af28-dl-eco",
        UHeight: 0,
        PartNumber: "IPC2124LB-AF28-DL-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 160,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2124LB-AF28-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC2124LB-AF28-ECO",
        Slug: "uniview-ipc2124lb-af28-eco",
        UHeight: 0,
        PartNumber: "IPC2124LB-AF28-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 140,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2124LB-AF28K-DL": {
        Manufacturer: "Uniview",
        Model: "IPC2124LB-AF28K-DL",
        Slug: "uniview-ipc2124lb-af28k-dl",
        UHeight: 0,
        PartNumber: "IPC2124LB-AF28K-DL",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 240,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2124LB-ASF28K-A": {
        Manufacturer: "Uniview",
        Model: "IPC2124LB-ASF28K-A",
        Slug: "uniview-ipc2124lb-asf28k-a",
        UHeight: 0,
        PartNumber: "IPC2124LB-ASF28K-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 330,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2124SB-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2124SB-ADF28KMC-I1",
        Slug: "uniview-ipc2124sb-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC2124SB-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 410,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2125LB-SF28(40)-A": {
        Manufacturer: "Uniview",
        Model: "IPC2125LB-SF28(40)-A",
        Slug: "uniview-ipc2125lb-sf2840-a",
        UHeight: 0,
        PartNumber: "IPC2125LB-SF28(40)-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 310,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2128SB-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2128SB-ADF28KMC-I1",
        Slug: "uniview-ipc2128sb-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC2128SB-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 420,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 11, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2312LE-ADF28K-WP-L": {
        Manufacturer: "Uniview",
        Model: "IPC2312LE-ADF28K-WP-L",
        Slug: "uniview-ipc2312le-adf28k-wp-l",
        UHeight: 0,
        PartNumber: "IPC2312LE-ADF28K-WP-L",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 290,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2312LE-ADF28KM-WP": {
        Manufacturer: "Uniview",
        Model: "IPC2312LE-ADF28KM-WP",
        Slug: "uniview-ipc2312le-adf28km-wp",
        UHeight: 0,
        PartNumber: "IPC2312LE-ADF28KM-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 470,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2314LE-ADF28K-WP-L": {
        Manufacturer: "Uniview",
        Model: "IPC2314LE-ADF28K-WP-L",
        Slug: "uniview-ipc2314le-adf28k-wp-l",
        UHeight: 0,
        PartNumber: "IPC2314LE-ADF28K-WP-L",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 300,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2314LE-ADF28K-WP-L2": {
        Manufacturer: "Uniview",
        Model: "IPC2314LE-ADF28K-WP-L2",
        Slug: "uniview-ipc2314le-adf28k-wp-l2",
        UHeight: 0,
        PartNumber: "IPC2314LE-ADF28K-WP-L2",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 280,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2314LE-ADF28KM-WP": {
        Manufacturer: "Uniview",
        Model: "IPC2314LE-ADF28KM-WP",
        Slug: "uniview-ipc2314le-adf28km-wp",
        UHeight: 0,
        PartNumber: "IPC2314LE-ADF28KM-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 460,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2318LE-ADF28KM-WP": {
        Manufacturer: "Uniview",
        Model: "IPC2318LE-ADF28KM-WP",
        Slug: "uniview-ipc2318le-adf28km-wp",
        UHeight: 0,
        PartNumber: "IPC2318LE-ADF28KM-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 480,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2322LP-ADEZK-DI": {
        Manufacturer: "Uniview",
        Model: "IPC2322LP-ADEZK-DI",
        Slug: "uniview-ipc2322lp-adezk-di",
        UHeight: 0,
        PartNumber: "IPC2322LP-ADEZK-DI",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 560,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 8, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2324LB-ADZK-H": {
        Manufacturer: "Uniview",
        Model: "IPC2324LB-ADZK-H",
        Slug: "uniview-ipc2324lb-adzk-h",
        UHeight: 0,
        PartNumber: "IPC2324LB-ADZK-H",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 510,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2324LP-ADEZK-DI": {
        Manufacturer: "Uniview",
        Model: "IPC2324LP-ADEZK-DI",
        Slug: "uniview-ipc2324lp-adezk-di",
        UHeight: 0,
        PartNumber: "IPC2324LP-ADEZK-DI",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 560,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 9, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC245LP-ADF40KC-WP": {
        Manufacturer: "Uniview",
        Model: "IPC245LP-ADF40KC-WP",
        Slug: "uniview-ipc245lp-adf40kc-wp",
        UHeight: 0,
        PartNumber: "IPC245LP-ADF40KC-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 870,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B14SE-ADF28K-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B14SE-ADF28K-WP-I1",
        Slug: "uniview-ipc2b14se-adf28k-wp-i1",
        UHeight: 0,
        PartNumber: "IPC2B14SE-ADF28K-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 890,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B14SE-ADF28KMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B14SE-ADF28KMC-WP-I1",
        Slug: "uniview-ipc2b14se-adf28kmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC2B14SE-ADF28KMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 920,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B14SE-ADZKMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B14SE-ADZKMC-WP-I1",
        Slug: "uniview-ipc2b14se-adzkmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC2B14SE-ADZKMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 980,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B14SS-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B14SS-ADF28KMC-I1",
        Slug: "uniview-ipc2b14ss-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC2B14SS-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 950,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B15SS-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B15SS-ADF28KMC-I1",
        Slug: "uniview-ipc2b15ss-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC2B15SS-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 970,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B18SE-ADF28K-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B18SE-ADF28K-WP-I1",
        Slug: "uniview-ipc2b18se-adf28k-wp-i1",
        UHeight: 0,
        PartNumber: "IPC2B18SE-ADF28K-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 930,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B18SE-ADF28KMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B18SE-ADF28KMC-WP-I1",
        Slug: "uniview-ipc2b18se-adf28kmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC2B18SE-ADF28KMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 920,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B18SE-ADZKMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B18SE-ADZKMC-WP-I1",
        Slug: "uniview-ipc2b18se-adzkmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC2B18SE-ADZKMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 860,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2B18SS-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC2B18SS-ADF28KMC-I1",
        Slug: "uniview-ipc2b18ss-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC2B18SS-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 970,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2K24SE-ADF40KMC-WL-I0": {
        Manufacturer: "Uniview",
        Model: "IPC2K24SE-ADF40KMC-WL-I0",
        Slug: "uniview-ipc2k24se-adf40kmc-wl-i0",
        UHeight: 0,
        PartNumber: "IPC2K24SE-ADF40KMC-WL-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 950,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2K28SE-ADF28KMC-DL-I0": {
        Manufacturer: "Uniview",
        Model: "IPC2K28SE-ADF28KMC-DL-I0",
        Slug: "uniview-ipc2k28se-adf28kmc-dl-i0",
        UHeight: 0,
        PartNumber: "IPC2K28SE-ADF28KMC-DL-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1050,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 13, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC2K28SE-ADF40KMC-WL-I0": {
        Manufacturer: "Uniview",
        Model: "IPC2K28SE-ADF40KMC-WL-I0",
        Slug: "uniview-ipc2k28se-adf40kmc-wl-i0",
        UHeight: 0,
        PartNumber: "IPC2K28SE-ADF40KMC-WL-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 960,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 13, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC312LP-ADF20KC-DL": {
        Manufacturer: "Uniview",
        Model: "IPC312LP-ADF20KC-DL",
        Slug: "uniview-ipc312lp-adf20kc-dl",
        UHeight: 0,
        PartNumber: "IPC312LP-ADF20KC-DL",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 250,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC314SB-ADF28KMC-DL-I1": {
        Manufacturer: "Uniview",
        Model: "IPC314SB-ADF28KMC-DL-I1",
        Slug: "uniview-ipc314sb-adf28kmc-dl-i1",
        UHeight: 0,
        PartNumber: "IPC314SB-ADF28KMC-DL-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 460,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 9, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC318SB-ADF28KMC-DL-I1": {
        Manufacturer: "Uniview",
        Model: "IPC318SB-ADF28KMC-DL-I1",
        Slug: "uniview-ipc318sb-adf28kmc-dl-i1",
        UHeight: 0,
        PartNumber: "IPC318SB-ADF28KMC-DL-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 470,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 9, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3224SS-ADF28K-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3224SS-ADF28K-I1",
        Slug: "uniview-ipc3224ss-adf28k-i1",
        UHeight: 0,
        PartNumber: "IPC3224SS-ADF28K-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 620,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC322LB-ASF28K-A": {
        Manufacturer: "Uniview",
        Model: "IPC322LB-ASF28K-A",
        Slug: "uniview-ipc322lb-asf28k-a",
        UHeight: 0,
        PartNumber: "IPC322LB-ASF28K-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 390,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC322LB-SF28-A": {
        Manufacturer: "Uniview",
        Model: "IPC322LB-SF28-A",
        Slug: "uniview-ipc322lb-sf28-a",
        UHeight: 0,
        PartNumber: "IPC322LB-SF28-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 350,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC324LB-ASF28K-A": {
        Manufacturer: "Uniview",
        Model: "IPC324LB-ASF28K-A",
        Slug: "uniview-ipc324lb-asf28k-a",
        UHeight: 0,
        PartNumber: "IPC324LB-ASF28K-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 280,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC325LB-SF28-A": {
        Manufacturer: "Uniview",
        Model: "IPC325LB-SF28-A",
        Slug: "uniview-ipc325lb-sf28-a",
        UHeight: 0,
        PartNumber: "IPC325LB-SF28-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 320,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3522LE-ADF28K-WP": {
        Manufacturer: "Uniview",
        Model: "IPC3522LE-ADF28K-WP",
        Slug: "uniview-ipc3522le-adf28k-wp",
        UHeight: 0,
        PartNumber: "IPC3522LE-ADF28K-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 510,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3524LE-ADF28K-WP": {
        Manufacturer: "Uniview",
        Model: "IPC3524LE-ADF28K-WP",
        Slug: "uniview-ipc3524le-adf28k-wp",
        UHeight: 0,
        PartNumber: "IPC3524LE-ADF28K-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 530,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3528LE-ADF28K-WP": {
        Manufacturer: "Uniview",
        Model: "IPC3528LE-ADF28K-WP",
        Slug: "uniview-ipc3528le-adf28k-wp",
        UHeight: 0,
        PartNumber: "IPC3528LE-ADF28K-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 580,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3532LP-ADEZK-DI": {
        Manufacturer: "Uniview",
        Model: "IPC3532LP-ADEZK-DI",
        Slug: "uniview-ipc3532lp-adezk-di",
        UHeight: 0,
        PartNumber: "IPC3532LP-ADEZK-DI",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 660,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3534LP-ADEZK-DI": {
        Manufacturer: "Uniview",
        Model: "IPC3534LP-ADEZK-DI",
        Slug: "uniview-ipc3534lp-adezk-di",
        UHeight: 0,
        PartNumber: "IPC3534LP-ADEZK-DI",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 660,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3605SB-ADF16KM-I0": {
        Manufacturer: "Uniview",
        Model: "IPC3605SB-ADF16KM-I0",
        Slug: "uniview-ipc3605sb-adf16km-i0",
        UHeight: 0,
        PartNumber: "IPC3605SB-ADF16KM-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 480,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3608SB-ADF16KM-I0": {
        Manufacturer: "Uniview",
        Model: "IPC3608SB-ADF16KM-I0",
        Slug: "uniview-ipc3608sb-adf16km-i0",
        UHeight: 0,
        PartNumber: "IPC3608SB-ADF16KM-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 480,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3612LB-AF28-DL-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC3612LB-AF28-DL-ECO",
        Slug: "uniview-ipc3612lb-af28-dl-eco",
        UHeight: 0,
        PartNumber: "IPC3612LB-AF28-DL-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 190,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3612LB-AF28-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC3612LB-AF28-ECO",
        Slug: "uniview-ipc3612lb-af28-eco",
        UHeight: 0,
        PartNumber: "IPC3612LB-AF28-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 190,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3612LB-AF28K-DL": {
        Manufacturer: "Uniview",
        Model: "IPC3612LB-AF28K-DL",
        Slug: "uniview-ipc3612lb-af28k-dl",
        UHeight: 0,
        PartNumber: "IPC3612LB-AF28K-DL",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 290,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3612LB-SF28-A": {
        Manufacturer: "Uniview",
        Model: "IPC3612LB-SF28-A",
        Slug: "uniview-ipc3612lb-sf28-a",
        UHeight: 0,
        PartNumber: "IPC3612LB-SF28-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 290,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3614LB-AF28-DL-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC3614LB-AF28-DL-ECO",
        Slug: "uniview-ipc3614lb-af28-dl-eco",
        UHeight: 0,
        PartNumber: "IPC3614LB-AF28-DL-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 230,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3614LB-AF28-ECO": {
        Manufacturer: "Uniview",
        Model: "IPC3614LB-AF28-ECO",
        Slug: "uniview-ipc3614lb-af28-eco",
        UHeight: 0,
        PartNumber: "IPC3614LB-AF28-ECO",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 190,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3614LB-AF28K-DL": {
        Manufacturer: "Uniview",
        Model: "IPC3614LB-AF28K-DL",
        Slug: "uniview-ipc3614lb-af28k-dl",
        UHeight: 0,
        PartNumber: "IPC3614LB-AF28K-DL",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 290,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3614LE-ADF28K-WP-L2": {
        Manufacturer: "Uniview",
        Model: "IPC3614LE-ADF28K-WP-L2",
        Slug: "uniview-ipc3614le-adf28k-wp-l2",
        UHeight: 0,
        PartNumber: "IPC3614LE-ADF28K-WP-L2",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 280,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3614SB-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3614SB-ADF28KMC-I1",
        Slug: "uniview-ipc3614sb-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC3614SB-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 470,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 11, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3615LB-SF28-A": {
        Manufacturer: "Uniview",
        Model: "IPC3615LB-SF28-A",
        Slug: "uniview-ipc3615lb-sf28-a",
        UHeight: 0,
        PartNumber: "IPC3615LB-SF28-A",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 280,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3618LB-ADF28K-G": {
        Manufacturer: "Uniview",
        Model: "IPC3618LB-ADF28K-G",
        Slug: "uniview-ipc3618lb-adf28k-g",
        UHeight: 0,
        PartNumber: "IPC3618LB-ADF28K-G",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 290,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3618SB-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3618SB-ADF28KMC-I1",
        Slug: "uniview-ipc3618sb-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC3618SB-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 470,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 12, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3622LE-ADF28K-WP": {
        Manufacturer: "Uniview",
        Model: "IPC3622LE-ADF28K-WP",
        Slug: "uniview-ipc3622le-adf28k-wp",
        UHeight: 0,
        PartNumber: "IPC3622LE-ADF28K-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 470,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3622LE-ADF28K-WP-L": {
        Manufacturer: "Uniview",
        Model: "IPC3622LE-ADF28K-WP-L",
        Slug: "uniview-ipc3622le-adf28k-wp-l",
        UHeight: 0,
        PartNumber: "IPC3622LE-ADF28K-WP-L",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 400,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3624LE-ADF28K-WP": {
        Manufacturer: "Uniview",
        Model: "IPC3624LE-ADF28K-WP",
        Slug: "uniview-ipc3624le-adf28k-wp",
        UHeight: 0,
        PartNumber: "IPC3624LE-ADF28K-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 480,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 3, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3624LE-ADF28K-WP-L": {
        Manufacturer: "Uniview",
        Model: "IPC3624LE-ADF28K-WP-L",
        Slug: "uniview-ipc3624le-adf28k-wp-l",
        UHeight: 0,
        PartNumber: "IPC3624LE-ADF28K-WP-L",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 410,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3628LE-ADF28K-WP": {
        Manufacturer: "Uniview",
        Model: "IPC3628LE-ADF28K-WP",
        Slug: "uniview-ipc3628le-adf28k-wp",
        UHeight: 0,
        PartNumber: "IPC3628LE-ADF28K-WP",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 480,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 4, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3634SE-ADF28K-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3634SE-ADF28K-WP-I1",
        Slug: "uniview-ipc3634se-adf28k-wp-i1",
        UHeight: 0,
        PartNumber: "IPC3634SE-ADF28K-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 670,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3634SE-ADF28KMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3634SE-ADF28KMC-WP-I1",
        Slug: "uniview-ipc3634se-adf28kmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC3634SE-ADF28KMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 820,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3634SE-ADZKMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3634SE-ADZKMC-WP-I1",
        Slug: "uniview-ipc3634se-adzkmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC3634SE-ADZKMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 850,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3634SS-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3634SS-ADF28KMC-I1",
        Slug: "uniview-ipc3634ss-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC3634SS-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 700,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3635SS-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3635SS-ADF28KMC-I1",
        Slug: "uniview-ipc3635ss-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC3635SS-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 690,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3638SE-ADF28K-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3638SE-ADF28K-WP-I1",
        Slug: "uniview-ipc3638se-adf28k-wp-i1",
        UHeight: 0,
        PartNumber: "IPC3638SE-ADF28K-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 690,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3638SE-ADF28KMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3638SE-ADF28KMC-WP-I1",
        Slug: "uniview-ipc3638se-adf28kmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC3638SE-ADF28KMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 820,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3638SE-ADZKMC-WP-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3638SE-ADZKMC-WP-I1",
        Slug: "uniview-ipc3638se-adzkmc-wp-i1",
        UHeight: 0,
        PartNumber: "IPC3638SE-ADZKMC-WP-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 990,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3638SS-ADF28KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC3638SS-ADF28KMC-I1",
        Slug: "uniview-ipc3638ss-adf28kmc-i1",
        UHeight: 0,
        PartNumber: "IPC3638SS-ADF28KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 690,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 10, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC3K28SE-ADF28KMC-DL-I0": {
        Manufacturer: "Uniview",
        Model: "IPC3K28SE-ADF28KMC-DL-I0",
        Slug: "uniview-ipc3k28se-adf28kmc-dl-i0",
        UHeight: 0,
        PartNumber: "IPC3K28SE-ADF28KMC-DL-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 860,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 13, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC6314LWH-AX5C-VG2": {
        Manufacturer: "Uniview",
        Model: "IPC6314LWH-AX5C-VG2",
        Slug: "uniview-ipc6314lwh-ax5c-vg2",
        UHeight: 0,
        PartNumber: "IPC6314LWH-AX5C-VG2",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 840,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 26, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC6324LWH-AX5C-VG2": {
        Manufacturer: "Uniview",
        Model: "IPC6324LWH-AX5C-VG2",
        Slug: "uniview-ipc6324lwh-ax5c-vg2",
        UHeight: 0,
        PartNumber: "IPC6324LWH-AX5C-VG2",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1330,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 26, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC815SB-ADF14K-I0": {
        Manufacturer: "Uniview",
        Model: "IPC815SB-ADF14K-I0",
        Slug: "uniview-ipc815sb-adf14k-i0",
        UHeight: 0,
        PartNumber: "IPC815SB-ADF14K-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 360,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 9, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC816SB-ADF16KMC-I1": {
        Manufacturer: "Uniview",
        Model: "IPC816SB-ADF16KMC-I1",
        Slug: "uniview-ipc816sb-adf16kmc-i1",
        UHeight: 0,
        PartNumber: "IPC816SB-ADF16KMC-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 440,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 9, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC8544EA-KM-I1": {
        Manufacturer: "Uniview",
        Model: "IPC8544EA-KM-I1",
        Slug: "uniview-ipc8544ea-km-i1",
        UHeight: 0,
        PartNumber: "IPC8544EA-KM-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2271,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 23, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "IPC8645EA-ADZKM-I1": {
        Manufacturer: "Uniview",
        Model: "IPC8645EA-ADZKM-I1",
        Slug: "uniview-ipc8645ea-adzkm-i1",
        UHeight: 0,
        PartNumber: "IPC8645EA-ADZKM-I1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 4770,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 31, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
    "IPC86CEB-AF18KC-I0": {
        Manufacturer: "Uniview",
        Model: "IPC86CEB-AF18KC-I0",
        Slug: "uniview-ipc86ceb-af18kc-i0",
        UHeight: 0,
        PartNumber: "IPC86CEB-AF18KC-I0",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 524,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 12, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC9312LFW-AF28-2X4": {
        Manufacturer: "Uniview",
        Model: "IPC9312LFW-AF28-2X4",
        Slug: "uniview-ipc9312lfw-af28-2x4",
        UHeight: 0,
        PartNumber: "IPC9312LFW-AF28-2X4",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1030,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 16, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC94144SR-X25-F40C": {
        Manufacturer: "Uniview",
        Model: "IPC94144SR-X25-F40C",
        Slug: "uniview-ipc94144sr-x25-f40c",
        UHeight: 0,
        PartNumber: "IPC94144SR-X25-F40C",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2270,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 24, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "IPC98246EFW-X42-W-VH1": {
        Manufacturer: "Uniview",
        Model: "IPC98246EFW-X42-W-VH1",
        Slug: "uniview-ipc98246efw-x42-w-vh1",
        UHeight: 0,
        PartNumber: "IPC98246EFW-X42-W-VH1",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 8400,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC IN", Label: "", Type: "dc-terminal", MaximumDraw: 74, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "microSD", Label: "", Position: "microSD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
