// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapssd = map[string]*DeviceData{
    "skon-din-1b": {
        Manufacturer: "SSD",
        Model: "skon-din-1b",
        Slug: "ssd-skon-din-1b",
        UHeight: 0,
        PartNumber: "130401-00083",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0.4,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "1", Label: "", Position: "1" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "skon-wall-1b": {
        Manufacturer: "SSD",
        Model: "skon-wall-1b",
        Slug: "ssd-skon-wall-1b",
        UHeight: 0,
        PartNumber: "130401-00077",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0.4,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "1", Label: "", Position: "1" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "skon-wall-4b": {
        Manufacturer: "SSD",
        Model: "skon-wall-4b",
        Slug: "ssd-skon-wall-4b",
        UHeight: 0,
        PartNumber: "130404-00012",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 3,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "1", Label: "", Position: "1" },
            { Name: "2", Label: "", Position: "2" },
            { Name: "3", Label: "", Position: "3" },
            { Name: "4", Label: "", Position: "4" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "skos-1u-3b": {
        Manufacturer: "SSD",
        Model: "skos-1u-3b",
        Slug: "ssd-skos-1u-3b",
        UHeight: 1,
        PartNumber: "130308-00048",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2.4,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "1", Label: "", Position: "1" },
            { Name: "2", Label: "", Position: "2" },
            { Name: "3", Label: "", Position: "3" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
