// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapvertiv = map[string]*DeviceData{
    "ACS8008SAC": {
        Manufacturer: "Vertiv",
        Model: "ACS8008SAC",
        Slug: "vertiv-acs8008sac",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "ttyS1", Type: "rj-45", Label: "" },
            { Name: "ttyS2", Type: "rj-45", Label: "" },
            { Name: "ttyS3", Type: "rj-45", Label: "" },
            { Name: "ttyS4", Type: "rj-45", Label: "" },
            { Name: "ttyS5", Type: "rj-45", Label: "" },
            { Name: "ttyS6", Type: "rj-45", Label: "" },
            { Name: "ttyS7", Type: "rj-45", Label: "" },
            { Name: "ttyS8", Type: "rj-45", Label: "" },
        },
        PowerPorts: []PowerPort{
            { Name: "ps1", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ACS8016DAC": {
        Manufacturer: "Vertiv",
        Model: "ACS8016DAC",
        Slug: "vertiv-acs8016dac",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "ttyS1", Type: "rj-45", Label: "" },
            { Name: "ttyS2", Type: "rj-45", Label: "" },
            { Name: "ttyS3", Type: "rj-45", Label: "" },
            { Name: "ttyS4", Type: "rj-45", Label: "" },
            { Name: "ttyS5", Type: "rj-45", Label: "" },
            { Name: "ttyS6", Type: "rj-45", Label: "" },
            { Name: "ttyS7", Type: "rj-45", Label: "" },
            { Name: "ttyS8", Type: "rj-45", Label: "" },
            { Name: "ttyS9", Type: "rj-45", Label: "" },
            { Name: "ttyS10", Type: "rj-45", Label: "" },
            { Name: "ttyS11", Type: "rj-45", Label: "" },
            { Name: "ttyS12", Type: "rj-45", Label: "" },
            { Name: "ttyS13", Type: "rj-45", Label: "" },
            { Name: "ttyS14", Type: "rj-45", Label: "" },
            { Name: "ttyS15", Type: "rj-45", Label: "" },
            { Name: "ttyS16", Type: "rj-45", Label: "" },
        },
        PowerPorts: []PowerPort{
            { Name: "ps1", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
            { Name: "ps2", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ACS8016SAC": {
        Manufacturer: "Vertiv",
        Model: "ACS8016SAC",
        Slug: "vertiv-acs8016sac",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "ttyS1", Type: "rj-45", Label: "" },
            { Name: "ttyS2", Type: "rj-45", Label: "" },
            { Name: "ttyS3", Type: "rj-45", Label: "" },
            { Name: "ttyS4", Type: "rj-45", Label: "" },
            { Name: "ttyS5", Type: "rj-45", Label: "" },
            { Name: "ttyS6", Type: "rj-45", Label: "" },
            { Name: "ttyS7", Type: "rj-45", Label: "" },
            { Name: "ttyS8", Type: "rj-45", Label: "" },
            { Name: "ttyS9", Type: "rj-45", Label: "" },
            { Name: "ttyS10", Type: "rj-45", Label: "" },
            { Name: "ttyS11", Type: "rj-45", Label: "" },
            { Name: "ttyS12", Type: "rj-45", Label: "" },
            { Name: "ttyS13", Type: "rj-45", Label: "" },
            { Name: "ttyS14", Type: "rj-45", Label: "" },
            { Name: "ttyS15", Type: "rj-45", Label: "" },
            { Name: "ttyS16", Type: "rj-45", Label: "" },
        },
        PowerPorts: []PowerPort{
            { Name: "ps1", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ACS8032SAC": {
        Manufacturer: "Vertiv",
        Model: "ACS8032SAC",
        Slug: "vertiv-acs8032sac",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "ttyS1", Type: "rj-45", Label: "" },
            { Name: "ttyS2", Type: "rj-45", Label: "" },
            { Name: "ttyS3", Type: "rj-45", Label: "" },
            { Name: "ttyS4", Type: "rj-45", Label: "" },
            { Name: "ttyS5", Type: "rj-45", Label: "" },
            { Name: "ttyS6", Type: "rj-45", Label: "" },
            { Name: "ttyS7", Type: "rj-45", Label: "" },
            { Name: "ttyS8", Type: "rj-45", Label: "" },
            { Name: "ttyS9", Type: "rj-45", Label: "" },
            { Name: "ttyS10", Type: "rj-45", Label: "" },
            { Name: "ttyS11", Type: "rj-45", Label: "" },
            { Name: "ttyS12", Type: "rj-45", Label: "" },
            { Name: "ttyS13", Type: "rj-45", Label: "" },
            { Name: "ttyS14", Type: "rj-45", Label: "" },
            { Name: "ttyS15", Type: "rj-45", Label: "" },
            { Name: "ttyS16", Type: "rj-45", Label: "" },
            { Name: "ttyS17", Type: "rj-45", Label: "" },
            { Name: "ttyS18", Type: "rj-45", Label: "" },
            { Name: "ttyS19", Type: "rj-45", Label: "" },
            { Name: "ttyS20", Type: "rj-45", Label: "" },
            { Name: "ttyS21", Type: "rj-45", Label: "" },
            { Name: "ttyS22", Type: "rj-45", Label: "" },
            { Name: "ttyS23", Type: "rj-45", Label: "" },
            { Name: "ttyS24", Type: "rj-45", Label: "" },
            { Name: "ttyS25", Type: "rj-45", Label: "" },
            { Name: "ttyS26", Type: "rj-45", Label: "" },
            { Name: "ttyS27", Type: "rj-45", Label: "" },
            { Name: "ttyS28", Type: "rj-45", Label: "" },
            { Name: "ttyS29", Type: "rj-45", Label: "" },
            { Name: "ttyS30", Type: "rj-45", Label: "" },
            { Name: "ttyS31", Type: "rj-45", Label: "" },
            { Name: "ttyS32", Type: "rj-45", Label: "" },
        },
        PowerPorts: []PowerPort{
            { Name: "ps1", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ACS8048DAC": {
        Manufacturer: "Vertiv",
        Model: "ACS8048DAC",
        Slug: "vertiv-acs8048dac",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "ttyS1", Type: "rj-45", Label: "" },
            { Name: "ttyS2", Type: "rj-45", Label: "" },
            { Name: "ttyS3", Type: "rj-45", Label: "" },
            { Name: "ttyS4", Type: "rj-45", Label: "" },
            { Name: "ttyS5", Type: "rj-45", Label: "" },
            { Name: "ttyS6", Type: "rj-45", Label: "" },
            { Name: "ttyS7", Type: "rj-45", Label: "" },
            { Name: "ttyS8", Type: "rj-45", Label: "" },
            { Name: "ttyS9", Type: "rj-45", Label: "" },
            { Name: "ttyS10", Type: "rj-45", Label: "" },
            { Name: "ttyS11", Type: "rj-45", Label: "" },
            { Name: "ttyS12", Type: "rj-45", Label: "" },
            { Name: "ttyS13", Type: "rj-45", Label: "" },
            { Name: "ttyS14", Type: "rj-45", Label: "" },
            { Name: "ttyS15", Type: "rj-45", Label: "" },
            { Name: "ttyS16", Type: "rj-45", Label: "" },
            { Name: "ttyS17", Type: "rj-45", Label: "" },
            { Name: "ttyS18", Type: "rj-45", Label: "" },
            { Name: "ttyS19", Type: "rj-45", Label: "" },
            { Name: "ttyS20", Type: "rj-45", Label: "" },
            { Name: "ttyS21", Type: "rj-45", Label: "" },
            { Name: "ttyS22", Type: "rj-45", Label: "" },
            { Name: "ttyS23", Type: "rj-45", Label: "" },
            { Name: "ttyS24", Type: "rj-45", Label: "" },
            { Name: "ttyS25", Type: "rj-45", Label: "" },
            { Name: "ttyS26", Type: "rj-45", Label: "" },
            { Name: "ttyS27", Type: "rj-45", Label: "" },
            { Name: "ttyS28", Type: "rj-45", Label: "" },
            { Name: "ttyS29", Type: "rj-45", Label: "" },
            { Name: "ttyS30", Type: "rj-45", Label: "" },
            { Name: "ttyS31", Type: "rj-45", Label: "" },
            { Name: "ttyS32", Type: "rj-45", Label: "" },
            { Name: "ttyS33", Type: "rj-45", Label: "" },
            { Name: "ttyS34", Type: "rj-45", Label: "" },
            { Name: "ttyS35", Type: "rj-45", Label: "" },
            { Name: "ttyS36", Type: "rj-45", Label: "" },
            { Name: "ttyS37", Type: "rj-45", Label: "" },
            { Name: "ttyS38", Type: "rj-45", Label: "" },
            { Name: "ttyS39", Type: "rj-45", Label: "" },
            { Name: "ttyS40", Type: "rj-45", Label: "" },
            { Name: "ttyS41", Type: "rj-45", Label: "" },
            { Name: "ttyS42", Type: "rj-45", Label: "" },
            { Name: "ttyS43", Type: "rj-45", Label: "" },
            { Name: "ttyS44", Type: "rj-45", Label: "" },
            { Name: "ttyS45", Type: "rj-45", Label: "" },
            { Name: "ttyS46", Type: "rj-45", Label: "" },
            { Name: "ttyS47", Type: "rj-45", Label: "" },
            { Name: "ttyS48", Type: "rj-45", Label: "" },
        },
        PowerPorts: []PowerPort{
            { Name: "ps1", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
            { Name: "ps2", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "ACS8048SAC": {
        Manufacturer: "Vertiv",
        Model: "ACS8048SAC",
        Slug: "vertiv-acs8048sac",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "ttyS1", Type: "rj-45", Label: "" },
            { Name: "ttyS2", Type: "rj-45", Label: "" },
            { Name: "ttyS3", Type: "rj-45", Label: "" },
            { Name: "ttyS4", Type: "rj-45", Label: "" },
            { Name: "ttyS5", Type: "rj-45", Label: "" },
            { Name: "ttyS6", Type: "rj-45", Label: "" },
            { Name: "ttyS7", Type: "rj-45", Label: "" },
            { Name: "ttyS8", Type: "rj-45", Label: "" },
            { Name: "ttyS9", Type: "rj-45", Label: "" },
            { Name: "ttyS10", Type: "rj-45", Label: "" },
            { Name: "ttyS11", Type: "rj-45", Label: "" },
            { Name: "ttyS12", Type: "rj-45", Label: "" },
            { Name: "ttyS13", Type: "rj-45", Label: "" },
            { Name: "ttyS14", Type: "rj-45", Label: "" },
            { Name: "ttyS15", Type: "rj-45", Label: "" },
            { Name: "ttyS16", Type: "rj-45", Label: "" },
            { Name: "ttyS17", Type: "rj-45", Label: "" },
            { Name: "ttyS18", Type: "rj-45", Label: "" },
            { Name: "ttyS19", Type: "rj-45", Label: "" },
            { Name: "ttyS20", Type: "rj-45", Label: "" },
            { Name: "ttyS21", Type: "rj-45", Label: "" },
            { Name: "ttyS22", Type: "rj-45", Label: "" },
            { Name: "ttyS23", Type: "rj-45", Label: "" },
            { Name: "ttyS24", Type: "rj-45", Label: "" },
            { Name: "ttyS25", Type: "rj-45", Label: "" },
            { Name: "ttyS26", Type: "rj-45", Label: "" },
            { Name: "ttyS27", Type: "rj-45", Label: "" },
            { Name: "ttyS28", Type: "rj-45", Label: "" },
            { Name: "ttyS29", Type: "rj-45", Label: "" },
            { Name: "ttyS30", Type: "rj-45", Label: "" },
            { Name: "ttyS31", Type: "rj-45", Label: "" },
            { Name: "ttyS32", Type: "rj-45", Label: "" },
            { Name: "ttyS33", Type: "rj-45", Label: "" },
            { Name: "ttyS34", Type: "rj-45", Label: "" },
            { Name: "ttyS35", Type: "rj-45", Label: "" },
            { Name: "ttyS36", Type: "rj-45", Label: "" },
            { Name: "ttyS37", Type: "rj-45", Label: "" },
            { Name: "ttyS38", Type: "rj-45", Label: "" },
            { Name: "ttyS39", Type: "rj-45", Label: "" },
            { Name: "ttyS40", Type: "rj-45", Label: "" },
            { Name: "ttyS41", Type: "rj-45", Label: "" },
            { Name: "ttyS42", Type: "rj-45", Label: "" },
            { Name: "ttyS43", Type: "rj-45", Label: "" },
            { Name: "ttyS44", Type: "rj-45", Label: "" },
            { Name: "ttyS45", Type: "rj-45", Label: "" },
            { Name: "ttyS46", Type: "rj-45", Label: "" },
            { Name: "ttyS47", Type: "rj-45", Label: "" },
            { Name: "ttyS48", Type: "rj-45", Label: "" },
        },
        PowerPorts: []PowerPort{
            { Name: "ps1", Label: "", Type: "iec-60320-c14", MaximumDraw: 35, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "eth1", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "GXT5-3000IRT2UXL": {
        Manufacturer: "Vertiv",
        Model: "GXT5-3000IRT2UXL",
        Slug: "vertiv-gxt5-3000irt2uxl",
        UHeight: 2,
        PartNumber: "GXT5-3000IRT2UXL",
        IsFullDepth: true,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 28.5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "USB", Type: "usb-b", Label: "", Poe: false },
            { Name: "RS232", Type: "rj-45", Label: "", Poe: false },
            { Name: "RS485", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Input Power", Label: "", Type: "iec-60320-c20", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Battery connector (EBC)", Label: "ebc-input", Type: "other", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Power Outlet - Non Programmable 1", Type: "iec-60320-c13", Label: "", PowerPort: "", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Power Outlet - Non Programmable 2", Type: "iec-60320-c13", Label: "", PowerPort: "", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Power Outlet - Programmable 1", Type: "iec-60320-c13", Label: "", PowerPort: "", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Power Outlet - Programmable 2", Type: "iec-60320-c13", Label: "", PowerPort: "", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Power Outlet - Programmable 3", Type: "iec-60320-c13", Label: "", PowerPort: "", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Power Outlet - Programmable 4", Type: "iec-60320-c13", Label: "", PowerPort: "", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Power Outlet - Non Programmable 15A", Type: "iec-60320-c19", Label: "", PowerPort: "", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Network Option (IntelliSlot Port)", Label: "", Type: "1000base-t", MgmtOnly: true },
        },
    },
    "MG01D4W1-36PT63-3PS6B2A10-S": {
        Manufacturer: "Vertiv",
        Model: "MG01D4W1-36PT63-3PS6B2A10-S",
        Slug: "vertiv-mg01d4w1-36pt63-3ps6b2a10-s",
        UHeight: 0,
        PartNumber: "GI10022L",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 7.26,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "iec-60309-p-n-e-4h", MaximumDraw: 7360, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "01", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "02", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "03", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "04", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "05", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "06", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "07", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "08", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "09", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "10", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "11", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "12", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "13", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "14", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "15", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "16", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "17", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "18", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "19", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "20", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "21", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "22", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "23", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "24", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "IMD", Label: "", Position: "0/IMD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "MPUIQ-VMCHS": {
        Manufacturer: "Vertiv",
        Model: "MPUIQ-VMCHS",
        Slug: "vertiv-mpuiq-vmchs",
        UHeight: 0,
        PartNumber: "520-854-504",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "KVM", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "usb0", Type: "usb-a", Label: "" },
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "SA1-01002": {
        Manufacturer: "Vertiv",
        Model: "SA1-01002",
        Slug: "vertiv-sa1-01002",
        UHeight: 1,
        PartNumber: "SA1-01002",
        IsFullDepth: false,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 544,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP0N3100": {
        Manufacturer: "Vertiv",
        Model: "VP0N3100",
        Slug: "vertiv-vp0n3100",
        UHeight: 1,
        PartNumber: "MN00X1R1-16MCQ9-3TL14A0A10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 6.8,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l14-30p", MaximumDraw: 5700, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Front circuit 1 outlet 1", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front circuit 1 outlet 2", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front circuit 2 outlet 1", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Front circuit 2 outlet 2", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 1 outlet 1", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 1 outlet 2", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 1 outlet 3", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 1 outlet 4", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 1 outlet 5", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 1 outlet 6", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 2 outlet 1", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 2 outlet 2", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 2 outlet 3", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 2 outlet 4", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 2 outlet 5", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Rear circuit 2 outlet 6", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP4N32A0": {
        Manufacturer: "Vertiv",
        Model: "VP4N32A0",
        Slug: "vertiv-vp4n32a0",
        UHeight: 2,
        PartNumber: "MN05M2R1-16IB48-3TL6A0H10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 6.35,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l6-30p", MaximumDraw: 4900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Circuit 1 outlet 1", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 2", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 3", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 4", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 5", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 6", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 7", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 8", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 1", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 2", Type: "iec-60320-c19", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 3", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 4", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 5", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 6", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 7", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 8", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "IMD", Label: "", Position: "0/IMD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP5N11A0": {
        Manufacturer: "Vertiv",
        Model: "VP5N11A0",
        Slug: "vertiv-vp5n11a0",
        UHeight: 1,
        PartNumber: "MNS5M1R5-06S153-1ST5A0H10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 4.54,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-5-15p", MaximumDraw: 1400, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "1", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "2", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "3", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "4", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "5", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "6", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP5N21A1": {
        Manufacturer: "Vertiv",
        Model: "VP5N21A1",
        Slug: "vertiv-vp5n21a1",
        UHeight: 1,
        PartNumber: "MNS5M1R5-12S203-2TL5A0H10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 4.54,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l5-20p", MaximumDraw: 1900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "1", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "2", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "3", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "4", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "5", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "6", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "7", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "8", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "9", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "10", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "11", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "12", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP5N31A0": {
        Manufacturer: "Vertiv",
        Model: "VP5N31A0",
        Slug: "vertiv-vp5n31a0",
        UHeight: 1,
        PartNumber: "MNS5M1R6-12S203-3TL5A0H10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 5.44,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l5-30p", MaximumDraw: 2800, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "1", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "2", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "3", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "4", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "5", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "6", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "7", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "8", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "9", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "10", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "11", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "12", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP5N31A1": {
        Manufacturer: "Vertiv",
        Model: "VP5N31A1",
        Slug: "vertiv-vp5n31a1",
        UHeight: 1,
        PartNumber: "MNS5M1R6-12CF18-3TL6A0H10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 6.35,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l6-30p", MaximumDraw: 4900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "1", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "2", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "3", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "4", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "5", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "6", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "7", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "8", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "9", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "10", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "11", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "12", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "IMD", Label: "", Position: "0/IMD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP7N31A1": {
        Manufacturer: "Vertiv",
        Model: "VP7N31A1",
        Slug: "vertiv-vp7n31a1",
        UHeight: 1,
        PartNumber: "MNU5M1R6-12CF18-3TL6A0H10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 6.35,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l6-30p", MaximumDraw: 4900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Circuit 1 outlet 1", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 2", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 3", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 4", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 5", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 6", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 1", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 2", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 3", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 4", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 5", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 6", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "IMD", Label: "", Position: "0/IMD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP7N32A0": {
        Manufacturer: "Vertiv",
        Model: "VP7N32A0",
        Slug: "vertiv-vp7n32a0",
        UHeight: 2,
        PartNumber: "MNU5MDR6-24CF18-3TL6A0H10-S",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 8.16,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l6-30p", MaximumDraw: 4900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "1", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "2", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "3", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "4", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "5", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "6", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "7", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "8", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "9", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "10", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "11", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "12", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "13", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "14", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "15", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "16", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "17", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "18", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "19", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "20", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "21", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "22", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "23", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "24", Type: "eaton-c39", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "IMD", Label: "", Position: "0/IMD" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP9562": {
        Manufacturer: "Vertiv",
        Model: "VP9562",
        Slug: "vertiv-vp9562",
        UHeight: 1,
        PartNumber: "BRN100-10",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2.72,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-5-15p", MaximumDraw: 1400, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "1", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "2", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "3", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "4", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "5", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "6", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "7", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "8", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "9", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "10", Type: "nema-5-15r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP9563": {
        Manufacturer: "Vertiv",
        Model: "VP9563",
        Slug: "vertiv-vp9563",
        UHeight: 1,
        PartNumber: "BRN100-1025",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2.72,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-5-20p", MaximumDraw: 1900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "1", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "2", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "3", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "4", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "5", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "6", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "7", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "8", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "9", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "10", Type: "nema-5-20r", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "VP9571A": {
        Manufacturer: "Vertiv",
        Model: "VP9571A",
        Slug: "vertiv-vp9571a",
        UHeight: 1,
        PartNumber: "XPR120-103C13TL6",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 3.63,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "nema-l6-30p", MaximumDraw: 4900, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "Circuit 1 outlet 1", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 2", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 3", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 4", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 5", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 1 outlet 6", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 1", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 2", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 3", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 4", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 5", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "Circuit 2 outlet 6", Type: "iec-60320-c13", Label: "", PowerPort: "Power", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
