// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapsprinter = map[string]*DeviceData{
    "Sprinter TX 19-24E1-2FE-DC48AC220": {
        Manufacturer: "Sprinter",
        Model: "Sprinter TX 19-24E1-2FE-DC48AC220",
        Slug: "sprinter-tx-19-24e1-2fe-dc48ac220",
        UHeight: 1,
        PartNumber: "Sprinter-TX-19-24E1-2FE-DC48AC220",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb", Type: "usb-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port2", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "port3", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/0", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/1", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/2", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/3", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/4", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/5", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/6", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/7", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/8", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/9", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/10", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/11", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/12", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/13", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/14", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/15", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/16", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/17", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/18", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/19", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/20", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/21", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/22", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "slot0/23", Label: "", Type: "e1", MgmtOnly: false },
        },
    },
    "Sprinter TX 48-2E1-2FE-AC220": {
        Manufacturer: "Sprinter",
        Model: "Sprinter TX 48-2E1-2FE-AC220",
        Slug: "sprinter-tx-48-2e1-2fe-ac220",
        UHeight: 1,
        PartNumber: "Sprinter-TX-48-2E1-2FE-AC220",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 0.55,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
            { Name: "usb", Type: "usb-b", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU", Label: "", Type: "iec-60320-c14", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "port0", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "port1", Label: "", Type: "1000base-x-sfp", MgmtOnly: false },
            { Name: "eth-0", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "eth-1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "e1-port1", Label: "", Type: "e1", MgmtOnly: false },
            { Name: "e1-port2", Label: "", Type: "e1", MgmtOnly: false },
        },
    },
}
