// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapgenexis = map[string]*DeviceData{
    "FiberTwist G2110-EU-2": {
        Manufacturer: "Genexis",
        Model: "FiberTwist G2110-EU-2",
        Slug: "genexis-fibertwist-g2110-eu-2",
        UHeight: 0,
        PartNumber: "99819025",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 132,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Power", Label: "", Type: "dc-terminal", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "GPON", Label: "", Type: "gpon", MgmtOnly: false },
            { Name: "LAN", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
