// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMappowercom = map[string]*DeviceData{
    "WOW-300": {
        Manufacturer: "Powercom",
        Model: "WOW-300",
        Slug: "powercom-wow-300",
        UHeight: 0,
        PartNumber: "WOW-300",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 1.9,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "Input", Label: "Input", Type: "ita-ef", MaximumDraw: 300, AllocatedDraw: 165 },
        },
        PowerOutlets: []PowerOutlet{
            { Name: "01", Type: "ita-f", Label: "", PowerPort: "Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "02", Type: "ita-f", Label: "", PowerPort: "Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
            { Name: "03", Type: "ita-f", Label: "", PowerPort: "Input", FeedLeg: "", MaximumDraw: 0, AllocatedDraw: 0 },
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
