// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapteltonika = map[string]*DeviceData{
    "RUT240": {
        Manufacturer: "Teltonika",
        Model: "RUT240",
        Slug: "teltonika-rut240",
        UHeight: 0,
        PartNumber: "RUT240",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 125,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "lan", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "mob1s1a1", Label: "", Type: "lte", MgmtOnly: false },
            { Name: "wan", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
    "RUT955": {
        Manufacturer: "Teltonika",
        Model: "RUT955",
        Slug: "teltonika-rut955",
        UHeight: 0,
        PartNumber: "RUT955",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 287,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "USB_1", Type: "usb-a", Label: "", Poe: false },
            { Name: "Sensor_1", Type: "other", Label: "", Poe: false },
            { Name: "Sensor_2", Type: "de-9", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "dc-terminal", MaximumDraw: 7, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "lan1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "lan2", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "lan3", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "mob1s1a1", Label: "", Type: "lte", MgmtOnly: false },
            { Name: "mob1s2a1", Label: "", Type: "lte", MgmtOnly: false },
            { Name: "wan", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "gnss_0", Label: "", Type: "other", MgmtOnly: false },
            { Name: "Wifi_2.4", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
            { Name: "Wifi_5", Label: "", Type: "ieee802.11ac", MgmtOnly: false },
        },
    },
    "RUTX09": {
        Manufacturer: "Teltonika",
        Model: "RUTX09",
        Slug: "teltonika-rutx09",
        UHeight: 0,
        PartNumber: "RUTX09",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 455,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "USB_1", Type: "usb-a", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "dc-terminal", MaximumDraw: 9, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "lan1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "lan2", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "lan3", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "mob1s1a1", Label: "", Type: "lte", MgmtOnly: false },
            { Name: "mob1s2a1", Label: "", Type: "lte", MgmtOnly: false },
            { Name: "wan", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "gnss_0", Label: "", Type: "other", MgmtOnly: false },
        },
    },
    "TRB500": {
        Manufacturer: "Teltonika",
        Model: "TRB500",
        Slug: "teltonika-trb500",
        UHeight: 0,
        PartNumber: "TRB500",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 241,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PS0", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "lan", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "mob1s1a1", Label: "", Type: "lte", MgmtOnly: false },
        },
    },
}
