// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapsonar = map[string]*DeviceData{
    "SNA-800": {
        Manufacturer: "Sonar",
        Model: "SNA-800",
        Slug: "sonar-sna-800",
        UHeight: 1,
        PartNumber: "SNA-800",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1.8,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
            { Name: "console", Type: "rj-45", Label: "", Poe: false },
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "PSU24V", Label: "", Type: "dc-terminal", MaximumDraw: 6, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "slot0/1", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/2", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/3", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/4", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/5", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/6", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/7", Label: "", Type: "100base-tx", MgmtOnly: false },
            { Name: "slot0/8", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
}
