// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapsmartlabs = map[string]*DeviceData{
    "SML-482 HD Base": {
        Manufacturer: "Smartlabs",
        Model: "SML-482 HD Base",
        Slug: "smartlabs-sml-482-hd-base",
        UHeight: 0,
        PartNumber: "sml-482-hd-base",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "parent",
        Weight: 140,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC", Label: "DC", Type: "dc-terminal", MaximumDraw: 15, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "ether1", Label: "1", Type: "100base-tx", MgmtOnly: false },
        },
    },
}
