// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMaproom_alert = map[string]*DeviceData{
    "32S Monitor": {
        Manufacturer: "Room Alert",
        Model: "32S Monitor",
        Slug: "room-alert-32s-monitor",
        UHeight: 1,
        PartNumber: "RA32S-RPD-RAS",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 1.36,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
            { Name: "DC Input", Label: "", Type: "dc-terminal", MaximumDraw: 5, AllocatedDraw: 0 },
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "Ethernet", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
}
