// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMaptelcord = map[string]*DeviceData{
    "KS-MP-4K-1U-BK": {
        Manufacturer: "Telcord",
        Model: "KS-MP-4K-1U-BK",
        Slug: "telcord-ks-mp-4k-1u-bk",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "parent",
        Weight: 1.5,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
            { Name: "SlotA", Label: "" },
            { Name: "SlotB", Label: "" },
            { Name: "SlotC", Label: "" },
            { Name: "SlotD", Label: "" },
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "MP-4K-6RJ-BK": {
        Manufacturer: "Telcord",
        Model: "MP-4K-6RJ-BK",
        Slug: "telcord-mp-4k-6rj-bk",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 188,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
            { Name: "Port 1", Label: "", Type: "8p8c", RearPort: "Port 1", RearPortPosition: 0 },
            { Name: "Port 2", Label: "", Type: "8p8c", RearPort: "Port 2", RearPortPosition: 0 },
            { Name: "Port 3", Label: "", Type: "8p8c", RearPort: "Port 3", RearPortPosition: 0 },
            { Name: "Port 4", Label: "", Type: "8p8c", RearPort: "Port 4", RearPortPosition: 0 },
            { Name: "Port 5", Label: "", Type: "8p8c", RearPort: "Port 5", RearPortPosition: 0 },
            { Name: "Port 6", Label: "", Type: "8p8c", RearPort: "Port 6", RearPortPosition: 0 },
        },
        RearPorts: []RearPort{
            { Name: "Port 1", Label: "", Type: "8p8c", Positions: 0, Poe: false },
            { Name: "Port 2", Label: "", Type: "8p8c", Positions: 0, Poe: false },
            { Name: "Port 3", Label: "", Type: "8p8c", Positions: 0, Poe: false },
            { Name: "Port 4", Label: "", Type: "8p8c", Positions: 0, Poe: false },
            { Name: "Port 5", Label: "", Type: "8p8c", Positions: 0, Poe: false },
            { Name: "Port 6", Label: "", Type: "8p8c", Positions: 0, Poe: false },
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
    "OK-4K-6QLC_U-2MPO_U-MM504-BK": {
        Manufacturer: "Telcord",
        Model: "OK-4K-6QLC_U-2MPO_U-MM504-BK",
        Slug: "telcord-ok-4k-6qlc-u-2mpo-u-mm504-bk",
        UHeight: 0,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "child",
        Weight: 342,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
            { Name: "Port q1p1", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 1 },
            { Name: "Port q1p2", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 2 },
            { Name: "Port q1p3", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 3 },
            { Name: "Port q1p4", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 4 },
            { Name: "Port q2p1", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 5 },
            { Name: "Port q2p2", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 6 },
            { Name: "Port q2p3", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 7 },
            { Name: "Port q2p4", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 8 },
            { Name: "Port q3p1", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 9 },
            { Name: "Port q3p2", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 10 },
            { Name: "Port q3p3", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 11 },
            { Name: "Port q3p4", Label: "", Type: "lc", RearPort: "Port 1", RearPortPosition: 12 },
            { Name: "Port q4p1", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 1 },
            { Name: "Port q4p2", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 2 },
            { Name: "Port q4p3", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 3 },
            { Name: "Port q4p4", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 4 },
            { Name: "Port q5p1", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 5 },
            { Name: "Port q5p2", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 6 },
            { Name: "Port q5p3", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 7 },
            { Name: "Port q5p4", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 8 },
            { Name: "Port q6p1", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 9 },
            { Name: "Port q6p2", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 10 },
            { Name: "Port q6p3", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 11 },
            { Name: "Port q6p4", Label: "", Type: "lc", RearPort: "Port 2", RearPortPosition: 12 },
        },
        RearPorts: []RearPort{
            { Name: "Port 1", Label: "", Type: "mpo", Positions: 12, Poe: false },
            { Name: "Port 2", Label: "", Type: "mpo", Positions: 12, Poe: false },
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
