// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapdiamond_sa = map[string]*DeviceData{
    "Diamond flexos BGT 3 &#43; 1HE": {
        Manufacturer: "Diamond SA",
        Model: "Diamond flexos BGT 3 &#43; 1HE",
        Slug: "diamond-sa-diamond-flexos-bgt-3-1he",
        UHeight: 4,
        PartNumber: "",
        IsFullDepth: false,
        Airflow: "",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 2.8,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "Slot 1", Label: "", Position: "1" },
            { Name: "Slot 2", Label: "", Position: "2" },
            { Name: "Slot 3", Label: "", Position: "3" },
            { Name: "Slot 4", Label: "", Position: "4" },
            { Name: "Slot 5", Label: "", Position: "5" },
            { Name: "Slot 6", Label: "", Position: "6" },
            { Name: "Slot 7", Label: "", Position: "7" },
            { Name: "Slot 8", Label: "", Position: "8" },
            { Name: "Slot 9", Label: "", Position: "9" },
            { Name: "Slot 10", Label: "", Position: "10" },
            { Name: "Slot 11", Label: "", Position: "11" },
            { Name: "Slot 12", Label: "", Position: "12" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
        },
    },
}
