// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapallnet = map[string]*DeviceData{
    "ALL2288": {
        Manufacturer: "Allnet",
        Model: "ALL2288",
        Slug: "allnet-all2288",
        UHeight: 0,
        PartNumber: "ALL2288",
        IsFullDepth: false,
        Airflow: "passive",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 180,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "LAN", Label: "", Type: "100base-tx", MgmtOnly: false },
        },
    },
}
