// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMaplanner = map[string]*DeviceData{
    "NCA-5330": {
        Manufacturer: "Lanner",
        Model: "NCA-5330",
        Slug: "lanner-nca-5330",
        UHeight: 1,
        PartNumber: "",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: false,
        RearImage: false,
        SubdeviceRole: "",
        Weight: 11.3,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
            { Name: "con0", Type: "rj-45", Label: "" },
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU0", Label: "", Position: "0" },
            { Name: "PSU1", Label: "", Position: "1" },
            { Name: "FAN0", Label: "", Position: "0" },
            { Name: "FAN1", Label: "", Position: "1" },
            { Name: "FAN2", Label: "", Position: "2" },
            { Name: "FAN3", Label: "", Position: "3" },
            { Name: "FAN4", Label: "", Position: "4" },
            { Name: "NIC Module Slot 0", Label: "", Position: "0" },
            { Name: "NIC Module Slot 1", Label: "", Position: "1" },
            { Name: "NIC Module Slot 2", Label: "", Position: "2" },
            { Name: "NIC Module Slot 3", Label: "", Position: "3" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "eth0", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
