// Code generated by go generate; DO NOT EDIT.
package devices

var DeviceTypesMapexxact = map[string]*DeviceData{
    "TS4-185599419": {
        Manufacturer: "Exxact",
        Model: "TS4-185599419",
        Slug: "exxact-ts4-185599419",
        UHeight: 4,
        PartNumber: "TS4-185599419",
        IsFullDepth: true,
        Airflow: "front-to-rear",
        FrontImage: true,
        RearImage: true,
        SubdeviceRole: "",
        Weight: 0,
        WeightUnit: "",
        IsPowered: false,
        ConsolePorts: []ConsolePort{
        },
        ConsoleServerPorts: []ConsoleServerPort{
        },
        PowerPorts: []PowerPort{
        },
        PowerOutlets: []PowerOutlet{
        },
        FrontPorts: []FrontPort{
        },
        RearPorts: []RearPort{
        },
        ModuleBays: []ModuleBay{
            { Name: "PSU1", Label: "", Position: "PSU1" },
            { Name: "PSU2", Label: "", Position: "PSU2" },
            { Name: "PSU3", Label: "", Position: "PSU3" },
            { Name: "PSU4", Label: "", Position: "PSU4" },
            { Name: "PCI-E 1", Label: "", Position: "1" },
            { Name: "PCI-E 2", Label: "", Position: "2" },
            { Name: "PCI-E 3", Label: "", Position: "3" },
            { Name: "PCI-E 4", Label: "", Position: "4" },
            { Name: "PCI-E 5", Label: "", Position: "5" },
            { Name: "PCI-E 6", Label: "", Position: "6" },
            { Name: "PCI-E 7", Label: "", Position: "7" },
            { Name: "PCI-E 8", Label: "", Position: "8" },
            { Name: "PCI-E 9", Label: "", Position: "9" },
            { Name: "PCI-E 10", Label: "", Position: "10" },
            { Name: "NVME 1", Label: "", Position: "11" },
            { Name: "NVME 2", Label: "", Position: "12" },
            { Name: "NVME 3", Label: "", Position: "13" },
            { Name: "NVME 4", Label: "", Position: "14" },
        },
			  DeviceBays: []DeviceBay{
        },
        InventoryItems: []InventoryItem{
        },
        Interfaces: []Interface{
            { Name: "BMC", Label: "", Type: "1000base-t", MgmtOnly: true },
            { Name: "1 Gig Ethernet 1", Label: "", Type: "1000base-t", MgmtOnly: false },
            { Name: "1 Gig Ethernet 2", Label: "", Type: "1000base-t", MgmtOnly: false },
        },
    },
}
